version: "3.9"

services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - micro-net

  mongo:
    image: mongo:8.0
    container_name: mongo-product
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo-product-data:/data/db
    networks:
      - micro-net

volumes:
  mongo-product-data:

networks:
  micro-net:
    driver: bridge
