version: "3.9"

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - micro-net

  mongo:
    image: mongo:8.0
    container_name: mongo-order
    restart: always
    ports:
      - "27020:27017" # map host 27019 to container 27017
    volumes:
      - mongo-order-data:/data/db
    networks:
      - micro-net

volumes:
  mongo-order-data:

networks:
  micro-net:
    driver: bridge
