version: "3.9"

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - micro-net

  mongo:
    image: mongo:8.0
    container_name: mongo-user
    restart: always
    ports:
      - "27018:27017" # map host 27018 to container 27017
    volumes:
      - mongo-user-data:/data/db
    networks:
      - micro-net

volumes:
  mongo-user-data:

networks:
  micro-net:
    driver: bridge
